// ============================================================
//  src/core/mockData.js  —  Mock data với poster thật từ TMDB
//  Dùng làm initial state cho screens — hiện đẹp ngay mà không
//  cần đợi Firebase load
// ============================================================

export const MOCK_MOVIES = [
  {
    id: 'mock-1',
    title: 'Dune: Part Two',
    genre: 'Sci-Fi',
    duration: 166,
    rating: 8.9,
    basePrice: 110000,
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    description: 'Cuộc chiến quyền lực và lời tiên tri trên hành tinh cát — trở lại hoành tráng hơn bao giờ hết.',
  },
  {
    id: 'mock-2',
    title: 'Inside Out 2',
    genre: 'Animation',
    duration: 100,
    rating: 8.2,
    basePrice: 90000,
    posterUrl: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    description: 'Hành trình cảm xúc mới của Riley — màu sắc rực rỡ và thông điệp ấm áp.',
  },
  {
    id: 'mock-3',
    title: 'Godzilla x Kong',
    genre: 'Action',
    duration: 115,
    rating: 7.6,
    basePrice: 100000,
    posterUrl: 'https://image.tmdb.org/t/p/w500/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg',
    description: 'Trận chiến quái vật đầy kỳ vĩ với hiệu ứng màn hình lớn bùng nổ.',
  },
  {
    id: 'mock-4',
    title: 'Deadpool & Wolverine',
    genre: 'Action',
    duration: 128,
    rating: 8.1,
    basePrice: 120000,
    posterUrl: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    description: 'Deadpool và Wolverine cùng nhau trong cuộc phiêu lưu đa vũ trụ hài hước và bùng nổ.',
  },
  {
    id: 'mock-5',
    title: 'Interstellar',
    genre: 'Sci-Fi',
    duration: 169,
    rating: 8.7,
    basePrice: 95000,
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIe.jpg',
    description: 'Hành trình vượt thời gian và không gian để cứu nhân loại khỏi tuyệt chủng.',
  },
  {
    id: 'mock-6',
    title: 'Spider-Man: No Way Home',
    genre: 'Action',
    duration: 148,
    rating: 8.3,
    basePrice: 105000,
    posterUrl: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    description: 'Peter Parker đối mặt với đa vũ trụ — cuộc chiến kinh điển nhất của Spider-Man.',
  },
];

export const MOCK_THEATERS = [
  {
    id: 'theater-1',
    name: 'Galaxy Nguyễn Du',
    address: '116 Nguyễn Du, Quận 1',
    city: 'TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
  },
  {
    id: 'theater-2',
    name: 'CGV Vincom Bà Triệu',
    address: '191 Bà Triệu, Hai Bà Trưng',
    city: 'Hà Nội',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&q=80',
  },
  {
    id: 'theater-3',
    name: 'Lotte Cinema Đà Nẵng',
    address: '6 Nhà Hát Trưng Vương, Hải Châu',
    city: 'Đà Nẵng',
    imageUrl: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=800&q=80',
  },
  {
    id: 'theater-4',
    name: 'BHD Star Phạm Ngọc Thạch',
    address: '284 Nam Kỳ Khởi Nghĩa, Quận 3',
    city: 'TP.HCM',
    imageUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&q=80',
  },
];

export const MOCK_SHOWTIMES = [
  {
    id: 'st-1',
    movieId: 'mock-1', movieTitle: 'Dune: Part Two',
    theaterId: 'theater-1', theaterName: 'Galaxy Nguyễn Du', theaterAddress: '116 Nguyễn Du, Quận 1',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    basePrice: 110000, startTime: '2026-04-15T10:00:00',
    room: 'Phòng 1', format: 'IMAX', language: 'Phụ đề',
    totalSeats: 64, availableSeats: 48,
  },
  {
    id: 'st-2',
    movieId: 'mock-1', movieTitle: 'Dune: Part Two',
    theaterId: 'theater-2', theaterName: 'CGV Vincom Bà Triệu', theaterAddress: '191 Bà Triệu, Hai Bà Trưng',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    basePrice: 110000, startTime: '2026-04-15T19:30:00',
    room: 'Phòng 3', format: '2D', language: 'Lồng tiếng',
    totalSeats: 64, availableSeats: 30,
  },
  {
    id: 'st-3',
    movieId: 'mock-2', movieTitle: 'Inside Out 2',
    theaterId: 'theater-1', theaterName: 'Galaxy Nguyễn Du', theaterAddress: '116 Nguyễn Du, Quận 1',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    basePrice: 90000, startTime: '2026-04-15T14:00:00',
    room: 'Phòng 2', format: '2D', language: 'Lồng tiếng',
    totalSeats: 64, availableSeats: 55,
  },
  {
    id: 'st-4',
    movieId: 'mock-3', movieTitle: 'Godzilla x Kong',
    theaterId: 'theater-2', theaterName: 'CGV Vincom Bà Triệu', theaterAddress: '191 Bà Triệu, Hai Bà Trưng',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg',
    basePrice: 100000, startTime: '2026-04-16T20:00:00',
    room: 'Phòng 5', format: '4DX', language: 'Phụ đề',
    totalSeats: 64, availableSeats: 20,
  },
  {
    id: 'st-5',
    movieId: 'mock-4', movieTitle: 'Deadpool & Wolverine',
    theaterId: 'theater-1', theaterName: 'Galaxy Nguyễn Du', theaterAddress: '116 Nguyễn Du, Quận 1',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    basePrice: 120000, startTime: '2026-04-16T21:30:00',
    room: 'Phòng 1', format: 'IMAX', language: 'Phụ đề',
    totalSeats: 64, availableSeats: 12,
  },
  {
    id: 'st-6',
    movieId: 'mock-5', movieTitle: 'Interstellar',
    theaterId: 'theater-3', theaterName: 'Lotte Cinema Đà Nẵng', theaterAddress: '6 Nhà Hát Trưng Vương, Hải Châu',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIe.jpg',
    basePrice: 95000, startTime: '2026-04-17T18:00:00',
    room: 'Phòng 4', format: '2D', language: 'Phụ đề',
    totalSeats: 64, availableSeats: 40,
  },
];

export const MOCK_TICKETS = [
  {
    id: 'ticket-mock-1',
    movieTitle: 'Dune: Part Two',
    theaterName: 'Galaxy Nguyễn Du',
    startTime: '2026-04-15T19:30:00',
    room: 'Phòng 3',
    seatCodes: 'C3, C4',
    totalPrice: 220000,
    originalPrice: 220000,
    discountAmount: 0,
    paymentMethod: 'Momo',
    status: 'booked',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    address: '116 Nguyễn Du, Quận 1',
    fullName: 'Nguyễn Văn A',
  },
  {
    id: 'ticket-mock-2',
    movieTitle: 'Deadpool & Wolverine',
    theaterName: 'Galaxy Nguyễn Du',
    startTime: '2026-04-16T21:30:00',
    room: 'Phòng 1',
    seatCodes: 'E5, E6, E7',
    totalPrice: 324000,
    originalPrice: 360000,
    discountAmount: 36000,
    promoCode: 'CINE10',
    paymentMethod: 'Ví điện tử',
    status: 'booked',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    address: '116 Nguyễn Du, Quận 1',
    fullName: 'Nguyễn Văn A',
  },
];
